# Description:
#
# Python script to fix/add haxe imports and package statements.
#

FROM python:2.7.14-alpine3.6
MAINTAINER dion@transition9.com

WORKDIR /app/
ADD haxe_imports_fix.py /app/haxe_imports_fix.py
